apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  # Tells ingress that this is a routing rule
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: posts.com
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: posts-srv
                port:
                  number: 4000
